//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myproject.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeUserDetail
    {
        public int employee_id { get; set; }
        public string employee_name { get; set; }
        public string employee_email { get; set; }
        public int employee_contactno { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string createdby { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
