//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetail
    {
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public int customer_phone { get; set; }
        public string customer_address { get; set; }
        public string customer_email { get; set; }
        public string customer_dob { get; set; }
        public string customer_gender { get; set; }
        public Nullable<bool> automobile_policy { get; set; }
        public Nullable<bool> vacation_policy { get; set; }
        public Nullable<bool> boat_coverage { get; set; }
        public Nullable<bool> motorcycle_coverage { get; set; }
        public Nullable<System.DateTime> registereddate { get; set; }
        public string createddate { get; set; }
    }
}
