//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerFamilyDetail
    {
        public string customer_family_id { get; set; }
        public string customer_id { get; set; }
        public string customer_name { get; set; }
        public string Family_membername { get; set; }
        public string customer_relation { get; set; }
        public string member_gender { get; set; }
        public string policy_member { get; set; }
        public Nullable<System.DateTime> registereddate { get; set; }
        public string createddate { get; set; }
    }
}
