//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myproject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GuviTrainingDatabaseEntities1 : DbContext
    {
        public GuviTrainingDatabaseEntities1()
            : base("name=GuviTrainingDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerDetail> CustomerDetails { get; set; }
        public virtual DbSet<CustomerFamilyDetail> CustomerFamilyDetails { get; set; }
        public virtual DbSet<EmployeeUserDetail> EmployeeUserDetails { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<uploadfiletable> uploadfiletables { get; set; }
    }
}
