//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uploadfiletable
    {
        public int fileid { get; set; }
        public Nullable<int> student_id { get; set; }
        public string filenamee { get; set; }
        public string contenttype { get; set; }
        public string filedata { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
    }
}
